### ISSUE TITLE
How do I generate a wallet address for my miner?

### ISSUE THREAD

**Issue by kladskull** [denaro-coin/denaro#1]

**Comment by skrtdev** [comment]
There is not a cli wallet yet. You can generate it manually with ECDSA P256. There is a wallet on telegram at t.me/DenaroCoinBot. A cli wallet is on the road

**Comment by skrtdev** [comment]
CLI wallet has just been released in https://github.com/denaro-coin/denaro/commit/5da8b057a15e97e8fc8b88396ef98e1e82bedbd3. Closing this
