### ISSUE TITLE
What is the correct values for the address parameter?

### ISSUE THREAD

**Issue by bombark** [denaro-coin/denaro#10]
python3 miner.py 123456
INFO:denaro:ic| 'sync blockchain'
INFO:denaro:ic| difficulty: Decimal('6.0')
521977.2952393586 hash/s
INFO:denaro:ic| i: 1000000
523573.2909438763 hash/s
INFO:denaro:ic| i: 2000000
521719.70132090384 hash/s
INFO:denaro:ic| i: 3000000
521440.30478519545 hash/s
INFO:denaro:ic| i: 4000000
520208.4286775026 hash/s
INFO:denaro:ic| i: 5000000
520507.49193837866 hash/s
INFO:denaro:ic| i: 6000000
520564.94910197187 hash/s
INFO:denaro:ic| i: 7000000
520317.60702107154 hash/s
INFO:denaro:ic| i: 8000000
520364.72357925103 hash/s
INFO:denaro:ic| i: 9000000
520258.4309129691 hash/s
INFO:denaro:ic| i: 10000000
519935.2588602538 hash/s
INFO:denaro:ic| i: 11000000
520152.0143620452 hash/s
INFO:denaro:ic| i: 12000000
519766.0066038589 hash/s
INFO:denaro:ic| i: 13000000
519658.6428831817 hash/s
INFO:denaro:ic| i: 14000000
517755.7227193395 hash/s
INFO:denaro:ic| i: 15000000
517484.1946772903 hash/s
INFO:denaro:ic| i: 16000000
517653.3308287877 hash/s
INFO:denaro:ic| i: 17000000
517879.16030931054 hash/s
INFO:denaro:ic| i: 18000000
INFO:denaro:ic| 'sync blockchain'
Traceback (most recent call last):
  File "/home/fgbombardelli/learning/criptocoin/denaro/miner.py", line 54, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/fgbombardelli/learning/criptocoin/denaro/miner.py", line 47, in run
    res = await push_block(None, _hex.hex(), [tx.hex() for tx in txs], False)
  File "/home/fgbombardelli/learning/criptocoin/denaro/denaro/node/main.py", line 266, in push_block
    txs = body['txs']
TypeError: 'Body' object is not subscriptable

**Comment by skrtdev** [comment]
Fixed in https://github.com/denaro-coin/denaro/commit/c0abcc505e541fd1b755f48201770ca71e5613c7. You can create an address using https://t.me/denarocoinbot or cli wallet (https://github.com/denaro-coin/denaro/tree/main/denaro/wallet)
