### ISSUE TITLE
I finally got it working. 

### ISSUE THREAD

**Issue by canhmai** [denaro-coin/denaro#6]
I finally got it working. 
SWEET !!
![image](https://user-images.githubusercontent.com/58513185/147951816-265cc806-7af5-4fd6-92a7-9343e67f6140.png)

**Comment by skrtdev** [comment]
Glad to see that. You can join telegram chat at https://t.me/denarogroup

**Comment by canhmai** [comment]
it's working but get some error ! 
![image](https://user-images.githubusercontent.com/58513185/148098207-09a74218-bf7e-44d5-b71d-d2132cd2a055.png)

**Comment by canhmai** [comment]
done !
![image](https://user-images.githubusercontent.com/58513185/148180257-2edfb982-eb8d-4e4a-80c3-f23f932fba5c.png)

**Comment by skrtdev** [comment]
> it's working but get some error ! IndexError: list index out of range sorry , i don't have telegram . do you have discord ? can we talk in discord ? ![image](https://user-images.githubusercontent.com/58513185/148099474-f82d95bf-5333-48f5-bc60-87a8be74166d.png)

It's the miner, you should run it with `python3 miner.py address`

**Comment by canhmai** [comment]
> It's the miner, you should run it with `python3 miner.py address`
sorry , i'm a newbie , Can you have a specific example?  
python3 miner.py address 
What does your address mean ?  wallet address or ip address ?
i can't run python3 wallet.py or is there any way to get the wallet address? Please help

**Comment by skrtdev** [comment]
You can use wallet.py or the telegram bot in order to get a wallet address
