### ISSUE TITLE
already a coin called denaro?

### ISSUE THREAD

**Issue by sheepdoglord554** [denaro-coin/denaro#8]
There is already a listed coin called Denaro with some PR material put out. They did an ICO in 2018. might be worth considering a name change if you're interested in going further with this.

**Comment by skrtdev** [comment]
Wasn't it called Denarius? Can you share some links of this denaro?

**Comment by sheepdoglord554** [comment]
its listed on Coinranking and on Twitter. It doesn't look like they've been active on social media in awhile but definitely out there.

https://coinranking.com/coin/twcGpGldH7nZp+denaro-dno

**Comment by skrtdev** [comment]
Their site https://denaro.io/ is just empty. Anyway it's a scam token on the ethereum blockchain

**Comment by sheepdoglord554** [comment]
Cool -- no worries then. This will be the **real** denaro
