### ISSUE TITLE
Need in depth description of how to build

### ISSUE THREAD

**Issue by NewtonJr4108** [denaro-coin/denaro#9]
Not quite experienced with docker and stuff like this but this is really interesting. Could you make like a video or leave a link for the downloads I need to run denaro? Thanks in advance.

**Comment by skrtdev** [comment]
If you're on linux, just install docker, git clone the repository, and run `make build` and `docker-compose up`.
It will run the node and postgres database, and you should be able to query your node using `curl localhost:3006`.
If it does work, run 'curl localhost:3006/sync_blockchain?node_url0https://denaro-node.gaetano.eu.org' and your node should start syncing. If you want your node to receive blocks and transactions without the need to sync, you should expose it publicly.

**Comment by NewtonJr4108** [comment]
Thx!
